function getSpeechRecognition(){return window.SpeechRecognition||window.webkitSpeechRecognition||null}
function startRecognition(onResult,onEnd){const SR=getSpeechRecognition();if(!SR){toast("Speech recognition is not supported in this browser. On iPhone, try the latest Safari and allow microphone access.");return}if(recognition)try{recognition.abort()}catch{};recognition=new SR();recognition.lang="en-US";recognition.interimResults=false;recognition.maxAlternatives=1;recognition.onresult=e=>onResult(e.results[0][0].transcript);recognition.onend=()=>onEnd?.();recognition.onerror=()=>toast("Microphone recognition did not complete.");recognition.start()}
function compareSpeech(expected,actual){const norm=s=>s.toLowerCase().replace(/[^a-z' ]/g,"").split(/\s+/).filter(Boolean);const e=norm(expected),a=norm(actual);const aset=new Set(a);const hit=e.filter(w=>aset.has(w)).length;const score=Math.round(hit/e.length*100);const html=e.map(w=>`<span class="${aset.has(w)?"token-ok":"token-miss"}">${w}</span>`).join(" ");return {score,html}}
function startShadowAttempt(){const expected=document.getElementById("shadowSentence").textContent;document.getElementById("shadowResult").textContent="Listening to you…";startRecognition(actual=>{const c=compareSpeech(expected,actual);document.getElementById("shadowResult").innerHTML=`<strong>${c.score}% word match</strong><br>${c.html}<br><small>I heard: ${esc(actual)}</small>`;state.attempts.pronunciation++;adjustSkill("speaking",c.score>=80?2:c.score>=55?.5:-.5);addXP(c.score>=80?10:4)},()=>{})}
function startSpeakingAttempt(){const prompt=currentUnit?.speaking?.[0]||"Tell me about your day.";document.getElementById("speakingResult").textContent=`Answer: ${prompt}`;startRecognition(actual=>{const wc=actual.trim().split(/\s+/).length;document.getElementById("speakingResult").innerHTML=`<strong>I heard:</strong> ${esc(actual)}<br><small>${wc} words. ${wc>=8?"Good length. Now try again with one target vocabulary word.":"Try adding one more detail."}</small>`;state.attempts.speaking++;adjustSkill("speaking",wc>=8?1.4:.4);addXP(6)})}
function checkWriting(){const text=document.getElementById("writingInput").value.trim();if(!text){toast("Write something first.");return}const words=text.split(/\s+/).filter(Boolean);const sentences=text.split(/[.!?]+/).filter(s=>s.trim());const cap=/^[A-Z]/.test(text);const end=/[.!?]$/.test(text);const target=currentUnit.vocab.map(v=>v[0]);const used=target.filter(w=>new RegExp(`\\b${w}\\b`,`i`).test(text));document.getElementById("writingFeedback").innerHTML=`<strong>Transparent check</strong><br>${words.length} words · ${sentences.length} sentence${sentences.length===1?"":"s"}<br>${cap?"✓":"○"} Starts with a capital · ${end?"✓":"○"} Ends with punctuation<br>${used.length?`✓ Used target words: ${used.join(", ")}`:"○ Try to use one target word"}<br><small>This free check does not pretend to be a full grammar model.</small>`;state.attempts.writing++;adjustSkill("writing",Math.min(2,words.length/20));addXP(5)}

async function loadLessonImage(term){const el=document.getElementById("lessonVisual");el.style.backgroundImage="linear-gradient(135deg,#253368,#1e2a54)";try{const url=`https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch=${encodeURIComponent(term)}&gsrnamespace=6&gsrlimit=8&prop=imageinfo&iiprop=url&iiurlwidth=1000&format=json&origin=*`;const r=await fetch(url);if(!r.ok)return;const j=await r.json();const pages=Object.values(j.query?.pages||{});const img=pages.find(p=>/\.(jpg|jpeg|png|webp)$/i.test(p.imageinfo?.[0]?.thumburl||p.imageinfo?.[0]?.url||""));const src=img?.imageinfo?.[0]?.thumburl||img?.imageinfo?.[0]?.url;if(src)el.style.backgroundImage=`linear-gradient(0deg,rgba(7,10,23,.76),rgba(7,10,23,.10)),url("${src}")`}catch{}}

async function askCoach(text){
  const messages=document.getElementById("coachMessages");messages.insertAdjacentHTML("beforeend",`<div class="coach-bubble user">${esc(text)}</div>`);const bot=document.createElement("div");bot.className="coach-bubble bot";bot.textContent="Thinking…";messages.appendChild(bot);messages.scrollTop=messages.scrollHeight;
  const local=await tryLocalGenerativeAI(text);if(local){bot.textContent=local}else bot.textContent=ruleCoach(text);messages.scrollTop=messages.scrollHeight
}
async function tryLocalGenerativeAI(text){
  try{
    const LM=window.LanguageModel||window.ai?.languageModel;if(!LM)return null;document.getElementById("coachModeLabel").textContent="On-device generative AI available";document.getElementById("coachDialogMode").textContent="On-device generative AI";const session=LM.create?await LM.create():await LM.create?.({});if(!session)return null;const prompt=`You are a concise English tutor. User CEFR estimate: ${state.level}. Weakest skill: ${weakestSkill()}. Explain in simple Arabic with short English examples. User asks: ${text}`;return await session.prompt(prompt)
  }catch{return null}
}
function ruleCoach(text){const t=text.toLowerCase(),weak=weakestSkill();if(/present perfect|have|has/.test(t))return "المضارع التام غالبًا يربط الماضي بالحاضر. مثال: I have finished my work. جرّب أن تكتب جملة عن شيء أنجزته اليوم.";if(/word|vocab|كلم/.test(t))return `مستواك الحالي ${state.level}. عندك كلمات تحتاج مراجعة: ${dueReviews().slice(0,3).map(x=>x.text).join(", ")||"لا يوجد الآن"}. راجعها بصوت مرتفع ثم استخدم كل كلمة في جملة.`;if(/listen|سمع|استماع/.test(t))return "في الاستماع: ابدأ بالتسجيل البشري إن وُجد، اسمع بسرعة 0.8× مرتين، ثم 1× دون قراءة النص. بعد ذلك افتح النص وتحقق مما فاتك.";if(/speak|نطق|تحدث/.test(t))return "اختر جملة قصيرة من الدرس. اسمعها، ثم اعمل Shadowing ثلاث مرات، وبعدها سجّل نفسك. لا تحاول إصلاح كل شيء مرة واحدة؛ ركّز على الإيقاع أولًا.";return `بناءً على تقدمك، أضع الأولوية الآن لمهارة ${skillLabel(weak)}. ابدأ بتدريب قصير 5–10 دقائق، ثم راجع كلمة واحدة صعبة بدل إضافة كلمات كثيرة.`}
function detectAIStatus(){const supported=!!(window.LanguageModel||window.ai?.languageModel);document.getElementById("aiStatus").textContent=supported?"On-device AI ready":"Adaptive Coach";document.getElementById("coachModeLabel").textContent=supported?"On-device generative AI available":"Local adaptive mode"}

function openPlacement(){placementIndex=0;placementScore=0;document.getElementById("placementDialog").showModal();renderPlacementQ()}
function renderPlacementQ(){const el=document.getElementById("placementStage");if(placementIndex>=PLACEMENT.length){const levels=["A1","A1","A2","B1","B1","B2","C1","C2","C2"];const lvl=levels[Math.min(placementScore,8)];state.level=lvl;const base={A1:10,A2:26,B1:43,B2:60,C1:76,C2:90}[lvl];Object.keys(state.skills).forEach(k=>state.skills[k]=base);state.onboarded=true;saveState();el.innerHTML=`<div class="empty-state"><div class="big-level">${lvl}</div><strong>Starting estimate</strong><p>Your level will keep adapting as you study. This is not an official CEFR certificate.</p><button id="placementDone" class="primary-btn">Start learning</button></div>`;document.getElementById("placementDone").onclick=()=>{document.getElementById("placementDialog").close();renderHome()};return}
  const q=PLACEMENT[placementIndex];el.innerHTML=`<div class="placement-question"><span class="eyebrow">QUESTION ${placementIndex+1} / ${PLACEMENT.length}</span><h3>${q.q}</h3>${q.options.map((o,i)=>`<button class="placement-option" data-pa="${i}">${esc(o)}</button>`).join("")}</div>`;el.querySelectorAll("[data-pa]").forEach(b=>b.onclick=()=>{if(+b.dataset.pa===q.a)placementScore++;placementIndex++;renderPlacementQ()})}

function updateBadges(){const d=dueReviews().length;const b=document.getElementById("reviewBadge");if(!b)return;b.textContent=d;b.classList.toggle("hidden",!d)}
function exportProgress(){const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`english-lab-progress-${todayKey()}.json`;a.click();URL.revokeObjectURL(a.href)}
function importProgress(file){const r=new FileReader();r.onload=()=>{try{state=Object.assign(clone(defaultState),JSON.parse(r.result));saveState();renderHome();toast("Progress imported") }catch{toast("Could not read this progress file")}};r.readAsText(file)}