function renderReview(filter="due"){
  let items=Object.values(state.reviews);if(filter==="due")items=dueReviews();if(filter==="hard")items=items.filter(x=>x.hard||state.hardWords[x.id]);items.sort((a,b)=>(a.due||0)-(b.due||0));
  const el=document.getElementById("reviewList");if(!items.length){el.innerHTML='<div class="empty-state">Nothing here yet. Tap any word in a lesson and add it to review.</div>';return}
  el.innerHTML=items.map(r=>`<article class="review-item"><div class="review-main"><strong>${esc(r.text)}</strong> <span class="due-pill">${reviewDueText(r.due)}</span><p dir="rtl">${esc(r.meaning||"")}</p></div><div class="review-actions"><button class="small-btn" data-rlisten="${r.id}">🔊 Voices</button><button class="small-btn" data-rhard="${r.id}">Hard</button><button class="small-btn" data-rgood="${r.id}">Good</button><button class="small-btn" data-reasy="${r.id}">Easy</button></div></article>`).join("");
  el.querySelectorAll("[data-rlisten]").forEach(b=>b.addEventListener("click",()=>openWord(b.dataset.rlisten)));
  el.querySelectorAll("[data-rhard]").forEach(b=>b.addEventListener("click",()=>reviewAnswer(b.dataset.rhard,0)));
  el.querySelectorAll("[data-rgood]").forEach(b=>b.addEventListener("click",()=>reviewAnswer(b.dataset.rgood,1)));
  el.querySelectorAll("[data-reasy]").forEach(b=>b.addEventListener("click",()=>reviewAnswer(b.dataset.reasy,2)));
}
function reviewDueText(ts){if(!ts||ts<=Date.now())return "Due now";const d=ts-Date.now();if(d<3600000)return `${Math.ceil(d/60000)} min`;if(d<86400000)return `${Math.ceil(d/3600000)} h`;return `${Math.ceil(d/86400000)} d`}
function reviewAnswer(id,rating){const r=state.reviews[id];if(!r)return;if(rating===0){r.wrong++;r.interval=10*60*1000;r.ease=Math.max(1.5,r.ease-.2);r.hard=true;adjustSkill("vocabulary",-.5)}else{r.correct++;const base=rating===2?3:1;r.interval=r.interval?Math.max(86400000,r.interval*r.ease*base):86400000*base;r.ease=Math.min(3,r.ease+(rating===2?.12:.03));adjustSkill("vocabulary",rating===2?1:.6)}r.due=Date.now()+r.interval;r.notified=false;addXP(rating===0?1:4);saveState();renderReview(document.querySelector("[data-review-filter].active")?.dataset.reviewFilter||"due")}

function renderGames(){
  const games=[{id:"match",icon:"🧩",name:"Word Match",desc:"Match English words with Arabic meanings."},{id:"scramble",icon:"🔀",name:"Sentence Builder",desc:"Put a sentence back in the correct order."},{id:"listen",icon:"🎧",name:"Listen & Choose",desc:"Hear a word, then choose what you heard."},{id:"speed",icon:"⚡",name:"Speed Review",desc:"Rapid-fire review from your saved vocabulary."}];
  document.getElementById("gameCards").innerHTML=games.map(g=>`<article class="game-card"><div class="game-icon">${g.icon}</div><h3>${g.name}</h3><p>${g.desc}</p><button class="secondary-btn" data-game="${g.id}">Play</button></article>`).join("");document.querySelectorAll("[data-game]").forEach(b=>b.addEventListener("click",()=>startGame(b.dataset.game)));
}
function reviewPool(){const saved=Object.values(state.reviews);if(saved.length>=4)return saved;const unit=levelUnits(state.level)[0]||UNITS[0];return unit.vocab.map(([w,m])=>({id:w,text:w,meaning:m}))}
function startGame(id){const pool=reviewPool();const stage=document.getElementById("gameStage");stage.classList.remove("hidden");if(id==="match"){const picks=pool.slice(0,4);stage.innerHTML=`<h3>Match the word</h3>${picks.map((x,i)=>`<button class="quiz-option" data-gm="${i}"><strong>${x.text}</strong> → ${x.meaning}</button>`).join("")}<p>Tap every pair once. This round is for speed and recall.</p>`;let count=0;stage.querySelectorAll("[data-gm]").forEach(b=>b.onclick=()=>{b.classList.add("correct");b.disabled=true;if(++count===picks.length){addXP(10);toast("Round complete +10 XP")}})}
  if(id==="scramble"){const u=levelUnits(state.level)[0]||UNITS[0];const sentence=u.grammar.example;const words=sentence.split(" ").sort(()=>Math.random()-.5);stage.innerHTML=`<h3>Rebuild the sentence</h3><div id="gameBuild" class="builder-line"></div><div class="word-bank">${words.map((w,i)=>`<button data-gw="${i}">${w}</button>`).join("")}</div><button id="gameCheck" class="primary-btn">Check</button>`;let built=[];stage.querySelectorAll("[data-gw]").forEach(b=>b.onclick=()=>{built.push(b.textContent);b.disabled=true;document.getElementById("gameBuild").textContent=built.join(" ")});document.getElementById("gameCheck").onclick=()=>{const n=s=>s.replace(/[^a-z ]/gi,"").toLowerCase().trim();if(n(built.join(" "))===n(sentence)){addXP(12);toast("Perfect +12 XP")}else toast("Try again")}}
  if(id==="listen"){
    const x=pool[Math.floor(Math.random()*pool.length)];
    const options=[x,...pool.filter(p=>p.id!==x.id).slice(0,2)].sort(()=>Math.random()-.5);
    stage.innerHTML=`<h3>Listen & choose</h3><p class="support-text">This game uses a real human recording only. If no open recording exists, the round will tell you instead of using synthetic speech.</p><button id="gameSpeak" class="secondary-btn">▶ Find human voice</button><div id="gameAudioStatus" class="mini-result">Ready.</div>${options.map((o,i)=>`<button class="quiz-option" data-go="${i}">${o.text}</button>`).join("")}`;
    document.getElementById("gameSpeak").onclick=async()=>{
      const status=document.getElementById("gameAudioStatus");status.textContent="Searching for a human recording…";
      const items=await fetchCommonsAudio(x.text);
      if(items.length){status.textContent=`Human speaker · ${items[0].accent||"accent not specified"}`;playRepeated(items[0].url)}
      else status.textContent="No reusable human recording was found for this word.";
    };
    stage.querySelectorAll("[data-go]").forEach((b,i)=>b.onclick=()=>{
      const ok=options[i].id===x.id;b.classList.add(ok?"correct":"wrong");
      if(ok){addXP(8);adjustSkill("listening",1);toast("Correct +8 XP")}else adjustSkill("listening",-.5)
    })
  }
  if(id==="speed"){let idx=0;const show=()=>{const x=pool[idx%pool.length];stage.innerHTML=`<h3>Speed review ${idx+1}/${Math.min(pool.length,8)}</h3><div class="big-level" style="font-size:42px">${x.text}</div><p dir="rtl">Do you remember the meaning?</p><button id="showMeaning" class="secondary-btn">Show meaning</button><div id="speedMeaning" class="mini-result hidden" dir="rtl">${x.meaning}</div><div class="dialog-actions"><button id="speedHard" class="secondary-btn">Hard</button><button id="speedGood" class="primary-btn">Good</button></div>`;document.getElementById("showMeaning").onclick=()=>document.getElementById("speedMeaning").classList.remove("hidden");document.getElementById("speedHard").onclick=()=>next(0);document.getElementById("speedGood").onclick=()=>next(1)};const next=r=>{if(state.reviews[pool[idx%pool.length].id])reviewAnswer(pool[idx%pool.length].id,r);idx++;if(idx>=Math.min(pool.length,8)){stage.innerHTML='<div class="empty-state">Speed round complete 🎉</div>';addXP(12)}else show()};show()}
}

function renderProgress(){const level=estimateLevel();document.getElementById("progressLevel").textContent=level;const weak=weakestSkill();document.getElementById("levelReason").textContent=`Based on your current skill average. ${skillLabel(weak)} is the main area holding the estimate back.`;document.getElementById("activityStats").innerHTML=`<div><strong>${Object.keys(state.completed).length}</strong><span>Lessons</span></div><div><strong>${Object.keys(state.reviews).length}</strong><span>Saved words</span></div><div><strong>${state.quizHistory.length}</strong><span>Checks</span></div>`;document.getElementById("progressSkills").innerHTML=Object.entries(state.skills).map(([k,v])=>`<div style="margin:12px 0"><div style="display:flex;justify-content:space-between"><strong>${skillLabel(k)}</strong><span>${Math.round(v)}%</span></div><div class="meter"><i style="width:${v}%"></i></div></div>`).join("");document.getElementById("levelJourney").innerHTML=LEVELS.map(l=>`<div class="journey-step ${l===level?"current":""}"><strong>${l}</strong><small>${LEVEL_NAMES[l]}</small><div class="meter"><i style="width:${state.progressByLevel[l]||0}%"></i></div></div>`).join("")}

function completeLesson(){if(!currentUnit)return;state.completed[currentUnit.id]=Date.now();const units=levelUnits(currentUnit.level);const done=units.filter(u=>state.completed[u.id]).length;state.progressByLevel[currentUnit.level]=Math.round(done/units.length*100);Object.keys(state.skills).forEach(k=>adjustSkill(k,.8));addXP(30);saveState();toast("Lesson complete +30 XP");setView("home")}